# Generated by Django 4.2 on 2024-06-07 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='end_at',
            field=models.DateField(default=datetime.date(2024, 6, 17)),
        ),
    ]
